### ISSUE TITLE
Are the plans still to have error detection released before the end of the year?

### ISSUE THREAD

**Issue by Coding-Cyanide** [Mattalabs/OctoPrint-Mattacloud#14]
Title.

**Comment by dougbrion** [comment]
Hello! Slowly more functionality is being tested and added. Hopefully the first part of the error detection pipeline will go live in the new year - a fun start to 2021! A version allowing control of up to 3 printers and adding print queues etc is just about to be launched and the error detection will be after that.
Sorry it is taking longer to test than expected mainly due to being very busy on my PhD also... Will keep you updated.

**Comment by Coding-Cyanide** [comment]
Absolutely no worries! I'm just glad to hear this project isn't abandoned.

Happy Holidays!
